In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
iris=np.loadtxt('iris.csv',skiprows=1,usecols=range(4),delimiter=',')

In [12]:
X=iris
y=np.array([0]*50+[1]*50+[2]*50)

In [13]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [15]:
from sklearn.neighbors import KNeighborsClassifier

In [17]:
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(X,y)
knn.score(X,y)

0.9666666666666667

In [18]:
pred_y=knn.predict(X)

In [19]:
(y!=pred_y).sum()

5

In [20]:
x[y!=pred_y]

array([[5.9, 3.2, 4.8, 1.8],
       [6.3, 2.5, 4.9, 1.5],
       [6. , 2.7, 5.1, 1.6],
       [4.9, 2.5, 4.5, 1.7],
       [6. , 2.2, 5. , 1.5]])

In [21]:
y[y!=pred_y]

array([1, 1, 1, 2, 2])

In [23]:
plt.figure(figsize=[12,8])
bad=X[y!=pred_y]
plt.scatter(bad[:,2],bad[:,3],marker='*',c='r',s=300)
plt.scatter(X[:,2],X[:,3]c=y)

SyntaxError: invalid syntax (<ipython-input-23-56d7838b7ec1>, line 4)