In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
from sklearn.datasets import load_iris

In [3]:
iris=load_iris()

In [6]:
dir(iris)

['DESCR', 'data', 'feature_names', 'target', 'target_names']

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X_train,X_test,y_train,y_test=train_test_split(iris.data,iris.target,shuffle=False)

In [10]:
np.bincount(y_test)

array([ 0,  0, 38], dtype=int64)

In [11]:
X_train,x_test,y_train,y_test=train_test_split(iris.data,iris.target,shuffle=True)

In [12]:
np.bincount(y_test)

array([11, 11, 16], dtype=int64)

In [13]:
X_train,x_test,y_train,y_test=train_test_split(iris.data,iris.target,test_size=50,shuffle=True)

In [14]:
np.bincount(y_test)

array([16, 17, 17], dtype=int64)